name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libltdl-dev zip unzip
          # Install Cython specifically for Kivy
          pip3 install --user --upgrade buildozer cython==0.29.33

      - name: Build with Buildozer
        working-directory: chatbot
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # This avoids the permission issues by running as the current runner user
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UOK-Chatbot-APK
          path: ./**/*.apk
